markdown: kramdown
highlighter: null
permalink: none
exclude: ["en-US/images/precompressed/", "node_modules", "Gruntfile.js", "package.json"]
url: http://silnrsi.github.io/silfontdev
#baseurl: /silfontdev
repourl: //github.com/silnrsi/silfontdev
title: SIL Font Development Guide
subtitle: How to build, modify, and contribute to SIL International font projects
